---
kind: pipeline
name: "Stage"

concurrency:
  limit: 2

steps:
  - name: "Test"
    image: node:10.11
    environment:
      NPM_AUTH_TOKEN:
        from_secret: drone_npm_auth_token
    commands:
      - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > .npmrc
      - npm -g install yarn
      - yarn install
      - yarn lint
      - yarn test:ci --collectCoverage=true

  - name: "Build"
    image: node:10.11
    commands:
      - echo ${DRONE_COMMIT_SHA:0:7} > .tags
      - export REACT_APP_GIT_SHA=$(cat .tags)
      - export BUILD_DOMAIN=$(cat .domains)
      - export BUILD_EXPIRE=$(date -d "+1 month" +%s000)
      - npm -g install yarn
      - yarn build

  - name: "Build container"
    image: plugins/docker
    environment:
      NPM_AUTH_TOKEN:
        from_secret: drone_npm_auth_token
      REACT_APP_BUILD_VERSION: Enterprise
    settings:
      registry: reg.openware.work
      repo: reg.openware.work/emirex/baseapp
      build_args_from_env:
        - REACT_APP_BUILD_VERSION
        - NPM_AUTH_TOKEN
      username:
        from_secret: ow_registry_username
      password:
        from_secret: ow_registry_password

  - name: "Redeploy on stage"
    image: rubykube/microkube:0.2.0
    environment:
      WEBHOOK_JWT_SECRET:
        from_secret: emirex_webhook_secret
    commands:
      - export latest_image=reg.openware.work/emirex/baseapp:$(cat .tags)
      - cd /home/app
      - bundle exec rake payload:send[frontend,$latest_image,http://emirex.openware.work:1337]

trigger:
  branch:
  - customer/emirex
  event:
  - push