---
kind: pipeline
name: "Test"
concurrency:
  limit: 1
trigger:
  event:
    - push

steps:
  - name: "Test & Build"
    image: node:12.13.1
    commands:
      - export REACT_APP_GIT_SHA=$(git rev-parse --short HEAD)
      - echo $REACT_APP_GIT_SHA > .tags
      - export BUILD_DOMAIN=$(cat .domains)
      - export BUILD_EXPIRE=$(date -d "+1 month" +%s000)
      - npm -g install yarn
      - yarn install
      - yarn lint
      - yarn test:ci --collectCoverage=true
      - yarn build

---
kind: pipeline
name: "Stable"
concurrency:
  limit: 1
trigger:
  event:
    - push
  branch:
    - 2-4-stable

steps:
  - name: "Write tag"
    image: quay.io/openware/sdk-citools:2.3.1
    environment:
      BRANCH_NAME: ${DRONE_BRANCH}
      REPO_NAME: ${DRONE_REPO}
      GITHUB_API_KEY:
        from_secret: kite_bot_key
    commands:
      - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile ci:prebuild

  - name: "Build docker image"
    image: plugins/gcr
    settings:
      repo:
        from_secret: gcr_frontend_repo
      json_key:
        from_secret: opendax_gcp_creds_base64
