variables:
  APP: "frontend"
  ENVIRONMENT: "ce3422"
  CONTEINER_REPO: "eu.gcr.io/emirex-preprod/ci-test"
  CONTAINER_BACKUP_IMAGE: $CONTEINER_REPO/$CI_REGISTRY_IMAGE/$CI_BUILD_REF_SLUG:$CI_COMMIT_SHORT_SHA
  CONTAINER_RELEASE_IMAGE: $CONTEINER_REPO/$CI_REGISTRY_IMAGE/$CI_BUILD_REF_SLUG:latest

stages:
  - build
  - deploy

compile:
  stage: build
  script:
    - docker build -t $CONTAINER_BACKUP_IMAGE -t $CONTAINER_RELEASE_IMAGE --build-arg REACT_APP_BUILD_VERSION=Enterprise --build-arg NPM_AUTH_TOKEN="$NPM_AUTH_TOKEN" --build-arg BUILD_DOMAIN=emirex.co .
    - echo $CONTAINER_BACKUP_IMAGE
    - docker push $CONTAINER_BACKUP_IMAGE
    - echo $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  tags:
    - staging

deploy-to-review:
  stage: deploy
  script:
    - echo "Deploy \"$APP\" docker-image \"$CONTAINER_RELEASE_IMAGE\" to \"$ENVIRONMENT\""
    - ansible-playbook ~/hetzner-cfg/emirex-apps/deploy.yaml --tags app -e env=$ENVIRONMENT -e charts=$APP
  tags:
    - staging

