image: docker:latest
services:
  - docker:dind

stages:
  - build
  - test
  - deploy
  - cleanup
 
compile:
  stage: build
  script:
    - docker build -t eu.gcr.io/emirex-preprod/ci-test/baseapp:"$CI_COMMIT_SHORT_SHA" --build-arg REACT_APP_BUILD_VERSION=Enterprise --build-arg NPM_AUTH_TOKEN="$NPM_AUTH_TOKEN" --build-arg BUILD_DOMAIN=emirex.com .
    - docker push eu.gcr.io/emirex-preprod/ci-test/baseapp:"$CI_COMMIT_SHORT_SHA"
 
testing:
  stage: test
  script:
    - echo "Testing"
 
deploy-to-review:
  stage: deploy
  script:
    - echo "Deploy docker-image with sources to rewiew"
    - apk add git
    - git clone git@gitlab.com:emirex-exchange/emirex-exchange-core-components/server-configs/hetzner-cfg.git
    - ./hetzner-cfg/emirex-apps/ansible-playbook deploy.yaml --tags app -e env=ce3422 -e charts=baseapp -e '{"extra-vars":{"baseapp":{"push eu.gcr.io/emirex-preprod/ci-test/baseapp":{"tag":"'"$CI_COMMIT_SHORT_SHA"'"}}}}'
  when: manual
 
deploy-to-prod:
  stage: deploy
  script:
    - echo "Deploy docker-image with sources to production"
  when: manual
 
cleanup:
  stage: cleanup
  when: always
  script:
    - echo "Stop & remove containers"
